"""Generate the dataset catalogue from configs/sources.yaml and configs/taxonomy.yaml.

    python -m telecomsafe.data.catalog

Writes data/README.md (Chinese), data/README-EN.md (English) and
reports/phase1/dataset_licences.csv. Never edit the READMEs by hand — change the
configs (English texts live in each entry's `en:` block) and re-run. Re-run after
downloading and after building so the "actual" counts are current.
"""

from __future__ import annotations

import csv
from collections import Counter
from pathlib import Path

from telecomsafe.paths import DATA, IMAGE_SUFFIXES, REPORTS, SPLITS, load_sources, load_taxonomy, resolve

TEXT = {
    "zh": {
        "title": "# 数据集说明 / Dataset Catalogue",
        "other": "> English version: [README-EN.md](README-EN.md)",
        "generated": "> 本文件由 `python -m telecomsafe.data.catalog` 根据 `configs/sources.yaml` 自动生成，**请勿手动编辑**。",
        "not_in_git": "> 数据本身不入库（见 `.gitignore`），按下文的获取方式下载到 `data/raw/<名称>/`。",
        "overview": "## 总览",
        "overview_head": "| 数据集 | 用途 | 参与构建 | 计划规模 | 本地原始张数 | 构建后张数 | 许可 | 链接 |",
        "home": "主页", "yes": "是", "no": "否", "not_downloaded": "未下载",
        "classes": "## 目标类别（阶段一）",
        "classes_head": "| id | 类别 | 维度 | 含义 | 判定标准 |",
        "details": "## 各数据集详情",
        "source": "来源", "self_built": "自建", "no_page": "无公开页面（见获取方式）", "paper": "论文",
        "desc": "简介", "size": "规模", "planned": "计划", "raw": "本地原始", "built": "构建后",
        "format": "格式 / 本地路径", "mapping": "类别映射", "annotates": "完整标注的目标类别",
        "pseudo_note": "（其余类别由 teacher 补伪标签）", "licence": "许可", "citation": "引用",
        "download": "获取方式", "use": "用途", "not_built": "（当前未参与构建）", "filter": "过滤", "notes": "备注",
        "unverified": "- ⚠️ 类别表与规模尚未按下载后的实际文件核对",
        "identity": "直接按目标类别标注", "map_todo": "待填写（下载后按数据集自带的类别表补全）", "drop": "丢弃",
        "or": "或", "roboflow": "Roboflow API：workspace `{ws}` / project `{pj}`",
        "ultralytics": "随 Ultralytics 的 `{yaml}` 自动下载", "manual": "手动：",
        "frozen": "- **冻结状态**：已冻结。{a}；{b}",
        "not_frozen": "- **冻结状态**：尚未冻结（标注完成后运行 `python -m telecomsafe.data.freeze_eval --create`）",
        "candidates": "- **候选图**：审阅后保留 telecom {telecom} 张、near {near} 张，待审阅 {pending} 张，已剔除 {rejected} 张（逐图许可见 `data/licence_manifest.csv`）",
        "unused": "## 调研过但阶段一未使用",
        "unused_head": "| 数据集 | 规模 | 许可 | 未使用原因 |",
        "roles": {"A": "训练 · A 核心", "B": "训练 · B 补充", "optional": "训练 · 可选", "eval": "测试（TelecomEval）", "unused": "未使用"},
        "eval_flow": [
            "## TelecomEval 建立流程",
            "",
            "1. `python -m telecomsafe.data.collect_open` —— 从 Openverse、Wikimedia Commons（含子分类）、Flickr、DVIDS 检索开放许可（CC0 / PD / CC BY / CC BY-SA）候选图，自动记录署名；Flickr、DVIDS 需要在 `.env` 填 key，否则跳过",
            "   `python -m telecomsafe.data.collect_video` —— 从 YouTube 的 CC 许可视频抽帧：只保留能看到完整人员（人框内有头部）的清晰帧，每段视频最多 4 帧",
            "2. `python -m telecomsafe.data.screen` —— 用 E2 数人、用 CLIP 判断场景并打分，生成 `data/raw/t3_candidates/review.html`；在网页中把每张图标为 Telecom / Near（电力线路作业，单独成子集）/ Reject，导出后运行 `python -m telecomsafe.data.screen --apply <导出的文件>`",
            "3. `python -m telecomsafe.data.pseudo_label --weights runs/phase1/e2/weights/best.pt --images data/raw/t3_candidates/images --yolo-out data/raw/t3_candidates/prelabels` —— 生成预标注（E2 标人员与 PPE，COCO 模型补车辆）",
            "4. `python -m telecomsafe.data.labelstudio serve` 启动 Label Studio（账号见 `.env`），另开终端 `python -m telecomsafe.data.labelstudio push` 导入筛选后保留的图片与预标注（之后新增的图用 `push --add`）",
            "5. 在 http://localhost:8080 逐张按上方「判定标准」修正：检查每个预标注框，补画漏标（安全带、机械没有预标注，必须手画）；不可用的图点 Skip",
            "6. `python -m telecomsafe.data.labelstudio pull` —— 导出为 YOLO 格式到 `data/raw/telecom_eval/`，并写出 `subsets.csv`（telecom / near）",
            "7. `python -m telecomsafe.data.freeze_eval --create` —— 冻结；此后只读，两个阶段共用",
        ],
    },
    "en": {
        "title": "# Dataset Catalogue",
        "other": "> 中文版：[README.md](README.md)",
        "generated": "> Generated by `python -m telecomsafe.data.catalog` from `configs/sources.yaml` — **do not edit by hand**.",
        "not_in_git": "> The data itself is not in git (see `.gitignore`); get each dataset into `data/raw/<name>/` as described below.",
        "overview": "## Overview",
        "overview_head": "| Dataset | Role | In build | Planned size | Local raw images | Images after build | Licence | Link |",
        "home": "homepage", "yes": "yes", "no": "no", "not_downloaded": "not downloaded",
        "classes": "## Target classes (phase 1)",
        "classes_head": "| id | Class | Dimension | Meaning | Decision criterion |",
        "details": "## Datasets in detail",
        "source": "Source", "self_built": "self-built", "no_page": "no public page (see Download)", "paper": "Paper",
        "desc": "Description", "size": "Size", "planned": "planned", "raw": "local raw", "built": "after build",
        "format": "Format / local path", "mapping": "Class mapping", "annotates": "Fully annotated target classes",
        "pseudo_note": " (other classes get teacher pseudo-labels)", "licence": "Licence", "citation": "Citation",
        "download": "Download", "use": "Role", "not_built": " (not in the build at present)", "filter": "Filter", "notes": "Notes",
        "unverified": "- ⚠️ Class list and size not yet checked against the downloaded files",
        "identity": "annotated directly with the target classes",
        "map_todo": "to be filled in (from the dataset's own class list after download)", "drop": "dropped",
        "or": "or", "roboflow": "Roboflow API: workspace `{ws}` / project `{pj}`",
        "ultralytics": "downloaded automatically with Ultralytics' `{yaml}`", "manual": "Manual: ",
        "frozen": "- **Frozen**: yes. {a}; {b}",
        "not_frozen": "- **Frozen**: not yet (run `python -m telecomsafe.data.freeze_eval --create` once annotation is done)",
        "candidates": "- **Candidates**: kept after review telecom {telecom} / near {near}, {pending} awaiting review, {rejected} rejected (per-image licences in `data/licence_manifest.csv`)",
        "unused": "## Surveyed but not used in phase 1",
        "unused_head": "| Dataset | Size | Licence | Why not used |",
        "roles": {"A": "training · A core", "B": "training · B supplementary", "optional": "training · optional",
                  "eval": "test (TelecomEval)", "unused": "not used"},
        "eval_flow": [
            "## Building TelecomEval",
            "",
            "1. `python -m telecomsafe.data.collect_open` — search Openverse, Wikimedia Commons (with subcategories), Flickr and DVIDS for openly licensed (CC0 / PD / CC BY / CC BY-SA) candidates; attribution is recorded automatically. Flickr and DVIDS need a key in `.env` and are skipped otherwise",
            "   `python -m telecomsafe.data.collect_video` — frames from Creative Commons YouTube videos: only sharp frames showing a whole person (a head inside the person box), at most 4 per video",
            "2. `python -m telecomsafe.data.screen` — counts people with E2, scores the scene with CLIP and writes `data/raw/t3_candidates/review.html`; mark each image Telecom / Near (power-line work, a separate subset) / Reject there, export, then run `python -m telecomsafe.data.screen --apply <exported file>`",
            "3. `python -m telecomsafe.data.pseudo_label --weights runs/phase1/e2/weights/best.pt --images data/raw/t3_candidates/images --yolo-out data/raw/t3_candidates/prelabels` — pre-labels (E2 labels people and PPE, a COCO model adds vehicles)",
            "4. `python -m telecomsafe.data.labelstudio serve` starts Label Studio (account in `.env`); in another terminal, `python -m telecomsafe.data.labelstudio push` imports the kept images and pre-labels (use `push --add` for images added later)",
            "5. At http://localhost:8080, correct every image against the decision criteria above: check each pre-label and add missing boxes (harness and machinery are never pre-labelled); Skip unusable images",
            "6. `python -m telecomsafe.data.labelstudio pull` — exports YOLO labels to `data/raw/telecom_eval/` and writes `subsets.csv` (telecom / near)",
            "7. `python -m telecomsafe.data.freeze_eval --create` — freeze; read-only afterwards and shared by both phases",
        ],
    },
}


def field(cfg: dict, key: str, lang: str, default: str = "—") -> str:
    """The English text from the entry's `en:` block when rendering English, else the original field."""
    if lang == "en" and key in (cfg.get("en") or {}):
        return cfg["en"][key]
    value = cfg.get(key)
    return default if value in (None, "") else value


def raw_count(cfg: dict) -> int | None:
    path = resolve(cfg.get("path", f"data/raw/{cfg['name']}"))
    if not path.exists():
        return None
    return sum(1 for p in path.rglob("*") if p.suffix.lower() in IMAGE_SUFFIXES)


def built_counts(stats: Path = REPORTS / "dataset_stats.csv") -> Counter:
    counts: Counter = Counter()
    if stats.exists():
        with open(stats, encoding="utf-8-sig") as f:
            for row in csv.DictReader(f):
                counts[row["source"]] += int(row["images"])
    return counts


def fmt_count(n: int | None, t: dict) -> str:
    return t["not_downloaded"] if n is None else f"{n:,}"


def class_map_text(cfg: dict, t: dict) -> str:
    cm = cfg.get("class_map")
    if cm == "identity":
        return t["identity"]
    if not cm:
        return t["map_todo"]
    return ", ".join(f"{k}→{v if v is not None else t['drop']}" for k, v in cm.items())


def download_text(cfg: dict, t: dict, lang: str) -> str:
    d = cfg.get("download") or {}
    m = d.get("method")
    script = f"`python -m telecomsafe.data.download --only {cfg['name']}`"
    wrap = (lambda x: f"（{x}）") if lang == "zh" else (lambda x: f" ({x})")
    if m == "kaggle":
        return f"`kaggle datasets download -d {d['ref']}`" + wrap(f"{t['or']} {script}")
    if m == "roboflow":
        return t["roboflow"].format(ws=d["workspace"], pj=d["project"]) + wrap(script)
    if m == "ultralytics":
        return t["ultralytics"].format(yaml=d["yaml"]) + wrap(script)
    if m == "manual":
        instructions = (cfg.get("en") or {}).get("instructions") if lang == "en" else None
        return t["manual"] + (instructions or d.get("instructions", ""))
    return "—"


def eval_status(t: dict) -> list[str]:
    lines = []
    sha = SPLITS / "telecom_eval.sha256"
    if sha.exists():
        head = sha.read_text(encoding="utf-8").splitlines()[:2]
        lines.append(t["frozen"].format(a=head[0].lstrip("# "), b=head[1].lstrip("# ")))
    else:
        lines.append(t["not_frozen"])
    manifest = DATA / "licence_manifest.csv"
    if manifest.exists():
        with open(manifest, encoding="utf-8-sig") as f:
            rows = list(csv.DictReader(f))
        state = Counter(r.get("subset") or "pending" for r in rows if r["status"] == "candidate")
        lines.append(t["candidates"].format(telecom=state["telecom"], near=state["near"], pending=state["pending"],
                                            rejected=sum(r["status"] == "rejected" for r in rows)))
    return lines


def render(sources: list[dict], taxonomy: list[dict], built: Counter, lang: str = "zh") -> str:
    t = TEXT[lang]
    roles = t["roles"]
    used = [c for c in sources if c.get("role") != "unused"]
    unused = [c for c in sources if c.get("role") == "unused"]
    out = [t["title"], "", t["other"], t["generated"], t["not_in_git"], "", t["overview"], "",
           t["overview_head"], "|---|---|---|---|---|---|---|---|"]
    for c in used:
        link = f"[{t['home']}]({c['homepage']})" if c.get("homepage") else "—"
        out.append(
            f"| `{c['name']}` {field(c, 'title', lang)} | {roles.get(c.get('tier'), c.get('tier', ''))} "
            f"| {t['yes'] if c.get('enabled') else t['no']} | {field(c, 'planned_size', lang)} "
            f"| {fmt_count(raw_count(c), t)} | {built.get(c['name'], '—')} | {field(c, 'licence', lang)} | {link} |"
        )

    out += ["", t["classes"], "", t["classes_head"], "|---|---|---|---|---|"]
    for i, c in enumerate(taxonomy):
        out.append(f"| {i} | `{c['name']}` | {c['dimension']} | {field(c, 'description', lang)} | {field(c, 'criterion', lang, '')} |")

    out += ["", t["details"]]
    for c in used:
        source = c.get("homepage") or (t["self_built"] if c.get("role") == "eval" else t["no_page"])
        out += ["", f"### `{c['name']}` — {field(c, 'title', lang)}", "", f"- **{t['source']}**: {source}"]
        if c.get("paper"):
            out.append(f"- **{t['paper']}**: {c['paper']}")
        out += [
            f"- **{t['desc']}**: {field(c, 'description', lang, '').strip()}",
            f"- **{t['size']}**: {t['planned']} {field(c, 'planned_size', lang)} ｜ {t['raw']} {fmt_count(raw_count(c), t)} "
            f"｜ {t['built']} {built.get(c['name'], '—')}",
            f"- **{t['format']}**: {c.get('format', '—')} ｜ `{c.get('path', '')}`",
            f"- **{t['mapping']}**: {class_map_text(c, t)}",
            f"- **{t['annotates']}**: {', '.join(c.get('annotates') or []) or '—'}"
            + (t["pseudo_note"] if c.get("role") == "train" else ""),
            f"- **{t['licence']}**: {field(c, 'licence', lang)}",
            f"- **{t['citation']}**: {field(c, 'citation', lang)}",
            f"- **{t['download']}**: {download_text(c, t, lang)}",
            f"- **{t['use']}**: {roles.get(c.get('tier'), '')}{'' if c.get('enabled') else t['not_built']}",
        ]
        if c.get("filter"):
            out.append(f"- **{t['filter']}**: {c['filter']}")
        if c.get("notes"):
            out.append(f"- **{t['notes']}**: {field(c, 'notes', lang)}")
        if not c.get("verified"):
            out.append(t["unverified"])
        if c.get("role") == "eval":
            out += eval_status(t)

    out += ["", t["unused"], "", t["unused_head"], "|---|---|---|---|"]
    for c in unused:
        out.append(f"| [{field(c, 'title', lang)}]({c['homepage']}) | {field(c, 'planned_size', lang)} "
                   f"| {field(c, 'licence', lang)} | {field(c, 'reason', lang, '')} |")

    out += ["", *t["eval_flow"], ""]
    text = "\n".join(out)
    # The Chinese version uses full-width colons after bold labels, as the rest of the Chinese docs do.
    return text.replace("**: ", "**：") if lang == "zh" else text


def write_licences(sources: list[dict], path: Path = REPORTS / "dataset_licences.csv") -> None:
    """English, for the report's References section."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        w = csv.writer(f)
        w.writerow(["name", "title", "tier", "enabled", "licence", "homepage", "citation"])
        for c in sources:
            w.writerow([c["name"], field(c, "title", "en"), c.get("tier"), c.get("enabled"), field(c, "licence", "en"),
                        c.get("homepage"), field(c, "citation", "en", "")])


def main() -> None:
    sources, taxonomy, built = load_sources(), load_taxonomy(), built_counts()
    DATA.mkdir(parents=True, exist_ok=True)
    (DATA / "README.md").write_text(render(sources, taxonomy, built, "zh"), encoding="utf-8")
    (DATA / "README-EN.md").write_text(render(sources, taxonomy, built, "en"), encoding="utf-8")
    write_licences(sources)
    print(f"wrote {DATA / 'README.md'}, {DATA / 'README-EN.md'} and {REPORTS / 'dataset_licences.csv'}")


if __name__ == "__main__":
    main()
